name: Artifact

on: [push]

env:
  ARTIFACT_NAME: myartifact
  
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        use: actions/checkout@v2
        
      - name: upload the artifact
        use: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
